// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'src/features/home/data/model/cart_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 7642841048266548864),
      name: 'CartModel',
      lastPropertyId: const obx_int.IdUid(5, 3419248245424603823),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 8771946861736197036),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 8947906570314030397),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 6720673069158855648),
            name: 'image',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 1793799748995723865),
            name: 'price',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 3419248245424603823),
            name: 'quantity',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(2, 7642841048266548864),
      lastIndexId: const obx_int.IdUid(0, 0),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [2442067212275245786],
      retiredIndexUids: const [],
      retiredPropertyUids: const [
        3135198281313536863,
        2824082222635931252,
        6218243644440689799,
        2756803107256473487,
        8597197758763519391
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    CartModel: obx_int.EntityDefinition<CartModel>(
        model: _entities[0],
        toOneRelations: (CartModel object) => [],
        toManyRelations: (CartModel object) => {},
        getId: (CartModel object) => object.id,
        setId: (CartModel object, int id) {
          object.id = id;
        },
        objectToFB: (CartModel object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final imageOffset = fbb.writeString(object.image);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addOffset(2, imageOffset);
          fbb.addFloat64(3, object.price);
          fbb.addInt64(4, object.quantity);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final imageParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final priceParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final quantityParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          final object = CartModel(
              id: idParam,
              name: nameParam,
              image: imageParam,
              price: priceParam,
              quantity: quantityParam);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [CartModel] entity fields to define ObjectBox queries.
class CartModel_ {
  /// See [CartModel.id].
  static final id =
      obx.QueryIntegerProperty<CartModel>(_entities[0].properties[0]);

  /// See [CartModel.name].
  static final name =
      obx.QueryStringProperty<CartModel>(_entities[0].properties[1]);

  /// See [CartModel.image].
  static final image =
      obx.QueryStringProperty<CartModel>(_entities[0].properties[2]);

  /// See [CartModel.price].
  static final price =
      obx.QueryDoubleProperty<CartModel>(_entities[0].properties[3]);

  /// See [CartModel.quantity].
  static final quantity =
      obx.QueryIntegerProperty<CartModel>(_entities[0].properties[4]);
}
